export const historicalWords = [
    "abbey", "abolition", "absolutism", "acropolis", "admiral", "agrarian", "alchemy", "alexandria", 
    "alliance", "allies", "amendment", "amphitheater", "anarchy", "ancient", "anglo-saxon", "annexation", 
    "antiquity", "apartheid", "apprentice", "archaeology", "archbishop", "architecture", "aristocracy", 
    "armada", "armistice", "artisan", "asylum", "athenian", "atlantis", "atrocities", "augustus", 
    "australopithecus", "autocracy", "autonomy", "avalon", "aztec", "babylon", "bastille", "battalion", 
    "bayonet", "beowulf", "berlin", "blacksmith", "blitzkrieg", "bolshevik", "bourgeoisie", "brigade", 
    "bronze", "brutus", "buddhism", "byzantine", "caliphate", "campaign", "canal", "capitol", "caravel", 
    "carthage", "catacombs", "cathedral", "cavalry", "celts", "centurion", "charter", "chateau", "chieftain", 
    "christendom", "chronicler", "city-state", "civilization", "clergy", "coalition", "colonial", "colony", 
    "colosseum", "commonwealth", "conclave", "conquistador", "conscription", "constitution", "consul", 
    "coronation", "council", "covenant", "cradle", "crusade", "czar", "dark ages", "declaration", "defenestration", 
    "democracy", "demography", "deposition", "despotism", "diplomacy", "dirigible", "discovery", "dynasty", 
    "ealdorman", "earldom", "edict", "emancipation", "empire", "enlightenment", "entente", "epidemic", 
    "epigraphy", "epoch", "expedition", "explorer", "famine", "fealty", "feudal", "fief", "fortress", 
    "fraternity", "freemason", "fresco", "frontier", "fugitive", "gaul", "geocentric", "ghetto", "gladiator", 
    "gothic", "governor", "grandeur", "guild", "hammurabi", "hansa", "hanseatic", "harvest", "hegemony", 
    "heliocentric", "heraldry", "heretic", "hieroglyph", "hinterland", "hominid", "horde", "horus", "huguenot", 
    "hyksos", "iconoclast", "illuminati", "imperial", "inauguration", "incan", "incendiary", "independence", 
    "indulgence", "industrial", "inquisition", "inscription", "interdict", "interregnum", "invasion", 
    "irrigation", "jarl", "jihad", "joan of arc", "joust", "judiciary", "jurisdiction", "kaiser", "kamikaze", 
    "keelboat", "kepler", "khanate", "knight", "knighthood", "landmark", "lapis lazuli", "latifundium", 
    "legion", "lenin", "lexicon", "liberation", "liberty", "lineage", "longship", "luddite", "lyceum", 
    "machinery", "magistrate", "magna carta", "maharaja", "manor", "manuscript", "margrave", "martyr", 
    "masons", "masonry", "mausoleum", "medieval", "megalith", "mercantile", "mercenary", "meridian", 
    "mesolithic", "messiah", "migration", "milestone", "militia", "millennium", "minaret", "mineral", 
    "missionary", "monastery", "monk", "monotheism", "monument", "mosaic", "mosque", "mummy", "municipality", 
    "musketeer", "mutiny", "mycenaean", "mythology", "napoleon", "nation", "nave", "necropolis", "neolithic", 
    "neptune", "nobleman", "nomad", "norman", "notary", "novice", "obelisk", "oath", "ode", "odyssey", 
    "oligarchy", "olympus", "oracle", "orator", "ordnance", "ossuary", "ottoman", "outlaw", "paleolithic", 
    "pandemic", "papacy", "parchment", "parliament", "parthenon", "partition", "patriarch", "patrician", 
    "patriot", "pax romana", "peasantry", "peninsula", "pennon", "pericles", "persian", "perspective", 
    "phalanx", "pharaoh", "philanthropy", "philosopher", "phoenician", "pilgrim", "plague", "plato", 
    "plebiscite", "plebeian", "polis", "politics", "polytheism", "pontiff", "population", "portcullis", 
    "praetor", "prelate", "presbyter", "preserve", "primogeniture", "prince", "princedom", "principality", 
    "proclamation", "proconsul", "proletariat", "prophecy", "proselyte", "providence", "provision", 
    "provisions", "prussia", "psalter", "pyramid", "pyre", "quarantine", "querilla", "quorum", "quotient", 
    "rabbi", "radiocarbon", "rafters", "raider", "reformation", "regalia", "regent", "regicide", "renaissance", 
    "republic", "revolution", "rhetoric", "roman", "romanesque", "rosetta stone", "rubicon", "ruins", 
    "sabbatical", "sacerdotal", "sacrifice", "sacristy", "sagas", "saga", "samurai", "sarcophagus", 
    "satrap", "savant", "saxon", "scapegoat", "schism", "scribe", "scriptorium", "sculpture", "secession", 
    "sect", "seigneur", "sepulchre", "serf", "serfdom", "settlement", "shaman", "siege", "signet", "silk road", 
    "sistine", "squire", "stadtholder", "stake", "stalemate", "statesman", "stele", "sterling", "stoa", 
    "stonehenge", "stratagem", "stronghold", "stucco", "succession", "suffrage", "sultan", "summit", 
    "sun king", "sun temple", "supreme court", "surveyor", "synod", "tablets", "talisman", "tapestry", 
    "tariff", "temple", "tetrarch", "theocracy", "thermopylae", "throne", "tiber", "tithe", "tombs", 
    "tournament", "trader", "tradition", "transcript", "trebuchet", "treaty", "tribe", "tribunal", "tribute", 
    "trireme", "trojan", "tsar", "tudor", "turret", "tyrant", "ulama", "ultimatum", "union", "urbanization", 
    "uruk", "usurp", "usury", "vassal", "venice", "vestal", "vikings", "viking", "village", "vindication", 
    "virgil", "visigoth", "vizier", "votive", "warrior", "warlord", "warrior-king", "writ", "writs", 
    "xerxes", "yeoman", "zarathustra", "zeus", "ziggurat", "zulu", "zephyr", "zodiac", "zoroastrian", 
    "zurich", "abacus", "abbess", "abbot", "abjure", "absolution", "accession", "acclaim", "accord", 
    "acoly"]  

    export const movieCharacters = [
        "IndianaJones", "JamesBond", "DarthVader", "LukeSkywalker", "HarryPotter", "HermioneGranger", 
        "RonWeasley", "FrodoBaggins", "Aragorn", "Gandalf", "Legolas", "BilboBaggins", "SamwiseGamgee", 
        "Gollum", "HanSolo", "PrincessLeia", "Yoda", "Obi-WanKenobi", "Chewbacca", "R2-D2", "C-3PO", 
        "AnakinSkywalker", "PadméAmidala", "EmperorPalpatine", "TheJoker", "Batman", "Superman", 
        "WonderWoman", "Spider-Man", "IronMan", "Thor", "CaptainAmerica", "Hulk", "BlackWidow", "Hawkeye", 
        "Thanos", "Loki", "DoctorStrange", "NickFury", "Gamora", "Star-Lord", "RocketRaccoon", "Groot", 
        "Drax", "ScarletWitch", "Vision", "Quicksilver", "Ant-Man", "Wasp", "BlackPanther", "Shuri", 
        "Killmonger", "DoctorOctopus", "GreenGoblin", "Sandman", "Venom", "Magneto", "ProfessorX", 
        "Wolverine", "Cyclops", "JeanGrey", "Storm", "Rogue", "Beast", "Mystique", "Nightcrawler", "Iceman", 
        "Joker", "HarleyQuinn", "PoisonIvy", "Catwoman", "Two-Face", "Riddler", "Penguin", "Bane", 
        "Scarecrow", "Mr.Freeze", "LuciusFox", "AlfredPennyworth", "RachelDawes", "CommissionerGordon", 
        "VitoCorleone", "MichaelCorleone", "SonnyCorleone", "FredoCorleone", "TomHagen", "KayAdams", 
        "ConnieCorleone", "JohnnyFontane", "Clemenza", "Tessio", "LucaBrasi", "Apollonia", "CaptainJackSparrow", 
        "WillTurner", "ElizabethSwann", "HectorBarbossa", "DavyJones", "JoshameeGibbs", "JamesNorrington", 
        "Calypso", "Blackbeard", "Angelica", "ScarlettO'Hara", "RhettButler", "AshleyWilkes", "MelanieHamilton", 
        "Mammie", "GeraldO'Hara", "EllenO'Hara", "SuellenO'Hara", "CarreenO'Hara", "FrankKennedy", 
        "CharlesHamilton", "PittypatHamilton", "IndiaWilkes", "BelleWatling", "AtticusFinch", "ScoutFinch", 
        "JemFinch", "BooRadley", "TomRobinson", "BobEwell", "MayellaEwell", "Calpurnia", "DillHarris", 
        "MaudieAtkinson", "AlexandraHancock", "SheriffTate", "NapoleonDynamite", "PedroSanchez", 
        "Deb", "UncleRico", "Kip", "LaFawnduh", "Rex", "Starr", "SummerWheatley", "Trisha", "DonLino", 
        "Oscar", "Lenny", "Angie", "Lola", "Ernie", "Sykes", "Bernie", "Frankie", "CrazyJoe", "DonEdwardLino", 
        "Shrek", "Donkey", "PrincessFiona", "LordFarquaad", "PussinBoots", "GingerbreadMan", "Pinocchio", 
        "ThreeLittlePigs", "BigBadWolf", "Dragon", "FairyGodmother", "PrinceCharming", "KingHarold", 
        "QueenLillian", "ArthurPendragon", "Doris", "Mulan", "Mushu", "LiShang", "ShanYu", "Cri-Kee", 
        "FaZhou", "FaLi", "GrandmotherFa", "Yao", "Ling", "Chien-Po", "TheEmperor", "Chi-Fu", "CaptainLiShang", 
        "Merida", "QueenElinor", "KingFergus", "TheWitch", "Angus", "Harris", "Hubert", "Hamish", "YoungMacGuffin", 
        "LordMacGuffin", "LordMacintosh", "LordDingwall", "Groot", "Rocket", "Yondu", "Nebula", "Ego", 
        "Mantis", "Kraglin", "Ronan", "Star-Lord", "Gamora", "Drax", "Angela", "Hawkeye", 
        "WinterSoldier", "PeggyCarter", "RedSkull", "Zemo", "Wong", "Dormammu", "TheAncientOne", 
        "Kaecilius", "Mordo", "NickFury", "MariaHill", "PhilCoulson", "Agent13", "ScarletWitch", 
        "Quicksilver", "Vision", "Ultron", "Thanos", "Nebula", "Loki", "Hela", "Grandmaster", "Surtur", 
        "Korg", "Valkyrie", "Odin", "Frigga", "Heimdall", "JaneFoster", "DarcyLewis", "ErikSelvig", 
        "Malekith", "Kurse", "Fandral", "Hogun", "Volstagg", "LadySif", "Skurge", "Spock", "Kirk", 
        "Bones", "Scotty", "Uhura", "Sulu", "Chekov", "Pike", "Khan", "Sarek", "AmandaGrayson", 
        "CarolMarcus", "Gaila", "GeorgeKirk", "WinonaKirk", "Gorn", "Garek", "T'Pol", "SevenofNine", 
        "Data", "Picard", "Riker", "Troi", "Worf", "LaForge", "Crusher", "WesleyCrusher", "Guinan", 
        "Q", "TashaYar", "ReginaldBarclay", "MilesO'Brien", "JakeSisko", "EzriDax", "Odo", "KiraNerys", 
        "Nog", "Garak", "ElimGarak", "Martok", "Weyoun", "Gowron", "JadziaDax", "Bashir", "Sisko", 
        "VicFontaine", "Rom", "Leeta", "Quark", "GulDukat", "Damar", "Ziyal", "Ghemor", "Torres", 
        "Paris", "Neelix", "Chakotay", "Janeway", "Kim", "Tuvok", "EMH", "Kes", "Seven", "MalcolmReynolds", 
        "ZoeWashburne", "HobanWashburne", "JayneCobb", "KayleeFrye", "SimonTam", "RiverTam", 
        "InaraSerra", "ShepherdBook", "Serenity", "Reavers", "JubalEarly", "Saffron", "Patience", 
        "Badger", "Niska", "Magneto", "Mystique", "Juggernaut", "Sabretooth", "Pyro", "Toad", "Destiny", 
        "Quicksilver", "ScarletWitch", "Blob", "OmegaRed", "Azazel", "Avalanche", "Mastermind", 
        "SilverSamurai", "LadyDeathstrike", "MisterSinister", "Apocalypse", "Banshee", "Sunfire", 
        "Havok", "Polaris", "Warpath", "EmmaFrost", "SebastianShaw", "MoiraMacTaggert", "Kraven", 
        "Sandman", "Mysterio", "Vulture", "GreenGoblin", "DoctorOctopus", "Lizard", "Electro", "Rhino", 
        "Shocker", "Kingpin", "Chameleon", "Scorpion", "Hobgoblin", "BlackCat", "SilverSable", "Hammerhead", 
        "Morbius", "Tombstone", "Venom", "Carnage", "Scream", "Phage", "Riot", "Lasher", "Agony", "Loki", 
        "Hela", "Fenrir", "Skurge", "Grandmaster", "Valkyrie", "Sif", "Korg", "Miek", "Odin", "Frigga", 
        "Thor", "Heimdall", "Fandral", "Hogun", "Volstagg", "JaneFoster", "DarcyLewis", "ErikSelvig", 
        "Thanos", "Ronan", "Nebula", "CorvusGlaive", "ProximaMidnight", "EbonyMaw"]